// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZiF6iHMpcOaNKVIFk2quEmpeih2k9OaY',
    appId: '1:852506302403:web:0e30526e839516af854f76',
    messagingSenderId: '852506302403',
    projectId: 'mescla-invest-fff3b',
    authDomain: 'mescla-invest-fff3b.firebaseapp.com',
    storageBucket: 'mescla-invest-fff3b.firebasestorage.app',
    measurementId: 'G-KQ7K20XWYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHrJQnA9mXOEaRbGBM_VIvuQhZjI2SFQ',
    appId: '1:852506302403:android:089566f595a4a050854f76',
    messagingSenderId: '852506302403',
    projectId: 'mescla-invest-fff3b',
    storageBucket: 'mescla-invest-fff3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBewgWlj3IQkQMHAMu3swKTuEiXOWVwiJg',
    appId: '1:852506302403:ios:cc4e2b3f831cbc5c854f76',
    messagingSenderId: '852506302403',
    projectId: 'mescla-invest-fff3b',
    storageBucket: 'mescla-invest-fff3b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
